config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources "entries"
  resources "researches"
  resources "technologies"
  resources "paintings"
  resources "members"
  resources "galleries"
  resources "blogs"
  resources "contacts"
  root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :title , :short_contents , :main_contents
  Blog.all.order("id desc").limit(1).each do |d|

  end
  def create
    Blog.create(blog_params)
  end
  private

  def blog_params
    params.require(:blog).permit(:image ,:title ,:short_contents , :main_contents)
  end
  belongs_to :entry
  mount_uploader :image, BlogUploader
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates_presence_of :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_presence_of :image , :name , :description
  def create
    Member.create(member_params)
  end
  private

  def member_params
    params.require(:member).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/new.rb
class New < ActiveRecord::Base

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  def create
    Painting.create(painting_params)
  end
  private

  def painting_params
    params.require(:painting).permit(:image)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/person.rb
class Person < ActiveRecord::Base
  def create
    Person.create(person_params)
  end
  private

  def person_params
    params.require(:people).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/research.rb
class Research < ActiveRecord::Base
  validates_presence_of :name , :contents , :main_contents
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title , :contents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @entries = Entry.all
    @blogs = Blog.all
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params["id"])
  end
  def create
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def edit
    @blog = Blog.find(params["id"])
  end
  def update
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.find(params["id"])
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def destroy
    blog = Blog.find(params["id"])
    @blog= Blog.destroy(blog)
    respond_to do |format|
      format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
      format.json { render :show, status: :ok, location: @blog }
      format.js
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @entries = Entry.all
    @researches = Research.all
    @technologies = Technology.all
    @paintings = Painting.all
    @members = Member.all
    @blogs =Blog.all
    @galleries = Gallery.all
    @entry =Entry.new
    @blog = Blog.new
    @research = Research.new
    @technology = Technology.new
    @member = Member.new
    @gallery = Gallery.new
  end

  def show
    @entry = Entry.all
  end

  def create
    entry_params = params[:entry].permit(:title)
    @entry = Entry.new(entry_params)
    respond_to do |format|
      if @entry.save
        format.html { redirect_to(entries_path(@entry), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @entry }
        format.js
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
        format.js
      end
    end
    end

  def edit
    @entry = Entry.find(params["id"])
  end
  def update
    entry_params = params[:entry].permit(:title)
    @entry = Entry.find(params["id"])
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to(entries_path(@entry), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @entry }
        format.js
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
        format.js
      end
    end

  end
  def destroy
    entry = Entry.find(params["id"])
    @entry= Entry.destroy(entry)
    respond_to do |format|
        format.html { redirect_to(entries_path(@entry), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @entry }
        format.js
    end
  end
  private
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "secret"
    end
  end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to entries_path
    end
    @entry = Entry.new
    @entries = Entry.all
    @researches = Research.all
    @technologies = Technology.all
    @paintings = Painting.all
    @members = Member.all
    @blogs =Blog.all
    @galleries = Gallery.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/blogs/_blog.html.erb
<div class="col-xs-12" id="blog_<%= blog.id %>">
  <div class="blog_medium">
        <article class="post">
          <div class="post_date">

            <span class="day"><%= blog.created_at.strftime("%d") %></span>
            <span class="month"><%= blog.created_at.strftime("%b") %></span>

          </div>

          <figure class="post_img">
              <%= image_tag blog.image_url(:large_avatar) if blog.image? %>
          </figure>
          <div class="post_content">
            <div class="post_meta">
              <h2>
                <%= blog.title %>
              </h2>
              <div class="metaInfo">
                <span><i class="fa"></i> Time :<%= blog.created_at.strftime("%H:%M") %> </span>
                <span><i class="fa"></i> Year :<%= blog.created_at.strftime("%Y") %></span>
              </div>
            </div>
            <p><%= blog.short_contents %></p>
            <div class="text-right"><a class="btn btn-small btn-default" href="<%= blogs_path %>">Read More</a></div>

          </div>

        </article>
  </div>
 <!-- <div style="color: #38B206;"><%= time_ago_in_words(blog.created_at) %></div> -->
  <div class="panel-body hidden" id="blog_div_<%= blog.id %>">
    <div class="btn-group" role="button" aria-label="...">
      <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myUpdateblog_<%= blog.id %>">Edit</button>
      <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" , remote: true%>
    </div>
  </div>
  <script>
      $("#blog_edit_btn").click(function() {
          $("#blog_div_<%= blog.id %>").removeClass('hidden');
          $("#blog_cancel_btn").removeClass('hidden');
      });
      $("#blog_cancel_btn").click(function() {
          $("#blog_div_<%= blog.id %>").addClass('hidden');
          $("#blog_cancel_btn").addClass('hidden');
      });
      $("#blog_up_btn").click(function() {
          $("#blog_div_<%= blog.id %>").addClass('hidden');
          $("#blog_cancel_btn").addClass('hidden');
      });
  </script>
  <!-- Modal -->
  <%= form_for(blog, :html => {:multipart => true} , :method => :put , remote: true , authenticity_token: true) do |f| %>
      <div class="modal fade" id="myUpdateblog_<%= blog.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Blog Update</h4>
            </div>
            <div class="modal-body">
              <div class="field">
                <%= f.label :HomePhoto %><br>
                <%= f.file_field :image, autofocus: true , class: "form-control" %>
              </div>
              <div class="field">
                <%= f.label :Title %><br>
                <%= f.text_field :title ,:required => true, placeholder: "Please input title" , :style => "font-size:small;" , class: "form-control" %>
              </div>
              <div class="field">
                <%= f.label :HomeContent %><br>
                <%= f.text_area :short_contents ,:required => true, :maxlength => 600, :rows => 4 , placeholder: "Maximum 600 words" , :style => "font-size:small;" , class: "form-control"%>
              </div>
              <div class="field">
                <%= f.label :BlogContent %><br>
                <%= f.text_area :main_contents,:required => true, :rows => 6 , placeholder: "Please input blog content" , :style => "font-size:small;" ,  class: "form-control" %>
              </div>
              <div class="field">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= submit_tag "Update", class:"btn btn-primary" , id:"blog_up_btn" %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <!-- modal -->

</div>

app/views/blogs/create.js.erb
$("#myBlog").modal('hide');
$(".blog_image").val('');
$(".blog_title").val('');
$(".blog_short_contents").val('');
$(".blog_main_contents").val('');
$("#my_tab_content").prepend('<%= j render @blog %>');
$("#blog_<%= @blog.id %>").hide().fadeIn(1000);

app/views/blogs/destroy.js.erb
$("#blog_<%= @blog.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/blogs/edit.html.erb
<%= form_for(@blog) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("Short contents") %></p>
    <p><%= form.text_area("short_contents") %></p>
    <p><%= form.label("Main Contents") %></p>
    <p><%= form.text_area("main_contents") %></p>
    <p><%= form.submit %></p>
<% end %>

app/views/blogs/index.html.erb
<!--start wrapper-->
<section class="wrapper">
  <section class="page_head">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          <h2>Blog Post</h2>
          <nav id="breadcrumbs">
            <ul>
              <li>Back To:</li>
              <li><a href="/">Home</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </section>

  <section class="content blog">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
          <div class="blog_single">
            <% for blog in Blog.all.order("id desc").each %>
                <article class="post">
                  <div class="post_date">
                    <span class="day"><%= blog.created_at.strftime("%d") %></span>
                    <span class="month"><%= blog.created_at.strftime("%b") %></span>
                  </div>
                  <div class="post_content">
                    <div class="post_meta">
                      <h2>
                        <%= blog.title %>
                      </h2>
                      <div class="metaInfo">
                        <span><i class="fa fa-calendar"></i> <a href="#"><%= blog.created_at.strftime("%b") %> <%= blog.created_at.strftime("%d") %>, <%= blog.created_at.strftime("%Y") %></a> </span>
                        <!-- <span><i class="fa fa-user"></i> By <a href="#">Louis</a> </span>
                         <span><i class="fa fa-tag"></i> <a href="#">Emin</a>, <a href="#">News</a> </span>
                         <span><i class="fa fa-comments"></i> <a href="#">12 Comments</a></span> -->
                      </div>
                    </div>
                    <p><%= blog.short_contents %></p>

                    <blockquote class="default">
                      <%= blog.main_contents %>
                    </blockquote>
                  </div>
                </article>
            <% end %>
          </div>
        </div>

     <!--Sidebar Widget-->
     <!-- <div class="col-xs-12 col-md-4 col-lg-4 col-sm-4">
          <div class="sidebar">
            <div class="widget widget_search">
              <div class="site-search-area">
                <form method="get" id="site-searchform" action="#">
                  <div>
                    <input class="input-text" name="s" id="s" placeholder="Enter Search keywords..." type="text" />
                    <input id="searchsubmit" value="Search" type="submit" />
                  </div>
                </form>
              </div>
            </div>

            <div class="widget widget_categories">
              <div class="widget_title">
                <h4><span>Categories</span></h4>
              </div>
              <ul class="arrows_list">
                <li><a href="#"><i class="fa fa-angle-right"></i> Grapic Design (10)</a></li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Web Design & Development (25)</a></li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Photography (29)</a></li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Custom Illustrations (19)</a></li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Wordpress Themes(38)</a></li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Videography (33)</a></li>
              </ul>
            </div>

          </div>
        </div> -->
      </div>
    </div> <!--/.container-->
  </section>

</section>
<!--end wrapper-->

app/views/blogs/new.html.erb
<%= form_for(Blog.new) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("Short contents") %></p>
    <p><%= form.text_area("short_contents") %></p>
    <p><%= form.label("Main Contents") %></p>
    <p><%= form.text_area("main_contents") %></p>
    <p><%= form.submit %></p>
<% end %>
<%= link_to("Back to all entries", entries_path) %>

app/views/blogs/show.html.erb
<h2><%= @research.title %></h2>
<p><%= @research.contents %></p>
<p><%= @research.containts %></p>
<p><%= link_to("Edit this entry", edit_research_path(@research)) %></p>
<p><%= link_to("Back to all entries", research_path) %></p>

app/views/blogs/update.js.erb
$("#myUpdateblog_<%= @blog.id %>").modal('hide');
$("#blog_<%= @blog.id %>").fadeOut(500, function(){

    $(this).remove();
    $("#my_tab_content").prepend('<%= j render @blog %>');
});

app/views/entries/_entry.html.erb
<ul class="nav navbar-nav" id="entry_<%= entry.id %>">
<li>
  <a href="#<%= entry.title %>"><%= best_in_place entry, :title %></a>
    <div class="btn-group hidden" role="button" aria-label="..." id="entry_div_<%= entry.id %>">
      <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myUpdateentry_<%= entry.id %>">Edit</button>
      <%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" , remote: true%>
    </div>
  <script>
      $("#entry_edit_btn").click(function() {
          $("#entry_div_<%= entry.id %>").removeClass('hidden');
          $("#entry_cancel_btn").removeClass('hidden');
      });
      $("#entry_cancel_btn").click(function() {
          $("#entry_div_<%= entry.id %>").addClass('hidden');
          $("#entry_cancel_btn").addClass('hidden');
      });
      $("#entry_up_btn").click(function() {
          $("#entry_div_<%= entry.id %>").addClass('hidden');
          $("#entry_cancel_btn").addClass('hidden');
      });
  </script>
  </li>
</ul>
<!-- Modal -->
<%= form_for(entry, :method => :put , remote: true) do |f| %>
    <div class="modal fade" id="myUpdateentry_<%= entry.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Menu Item Update</h4>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :Name %><br>
              <%= f.text_field :title , autofocus: true ,:required => true, placeholder: "Please input title", :size =>"45x2", :style => "font-size:small;" , class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Update", class:"btn btn-primary" , id: "entry_up_btn" %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<!-- modal -->

app/views/entries/create.js.erb
$("#myMenu").modal('hide');
$(".entry_title").val('');
$("#my_menu").prepend('<%= j render @entry %>')
$("#entry_<%= @entry.id %>").hide().fadeIn(1000)

app/views/entries/destroy.js.erb
$("#entry_<%= @entry.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
    <p><%= form.label("Hyper Link") %></p>
    <p><%= form.text_field("link") %></p>
    <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("Hype link") %></p>
    <p><%= form.text_area("link") %></p>
    <p><%= form.submit %></p>
<% end %>

<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%=@entry.title %></h2>
<p><%= @entry.date %></p>
<p><%= @entry.contents %></p>
<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/update.js.erb
$("#myUpdateentry_<%= @entry.id %>").modal('hide');
$("#entry_<%= @entry.id %>").fadeOut(500, function(){
    $(this).remove();
    $("#my_menu").prepend('<%= j render @entry %>');
});