config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources "entries"
  resources "researches"
  resources "technologies"
  resources "paintings"
  resources "members"
  resources "galleries"
  resources "blogs"
  resources "contacts"
  root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :title , :short_contents , :main_contents
  Blog.all.order("id desc").limit(1).each do |d|

  end
  def create
    Blog.create(blog_params)
  end
  private

  def blog_params
    params.require(:blog).permit(:image ,:title ,:short_contents , :main_contents)
  end
  belongs_to :entry
  mount_uploader :image, BlogUploader
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates_presence_of :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_presence_of :image , :name , :description
  def create
    Member.create(member_params)
  end
  private

  def member_params
    params.require(:member).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/new.rb
class New < ActiveRecord::Base

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  def create
    Painting.create(painting_params)
  end
  private

  def painting_params
    params.require(:painting).permit(:image)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/person.rb
class Person < ActiveRecord::Base
  def create
    Person.create(person_params)
  end
  private

  def person_params
    params.require(:people).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/research.rb
class Research < ActiveRecord::Base
  validates_presence_of :name , :contents , :main_contents
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title , :contents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to entries_path
    end
    @entry = Entry.new
    @entries = Entry.all
    @researches = Research.all
    @technologies = Technology.all
    @paintings = Painting.all
    @members = Member.all
    @blogs =Blog.all
    @galleries = Gallery.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/contacts/_contact.html.erb
<div class="col-md-3 col-sm-6" id="contact_<%= contact.id %>">
  <div class="serviceBox_1">
    <div class="icon_service">
      <i class="fa fa-home"></i>
      <h3><%= best_in_place contact, :title %></h3>
    </div>
    <div class="fr_content">
      <p>
        <%= best_in_place contact, :contents %>
      </p>

    </div>
  </div>
  <div style="color: #38B206;"><%= time_ago_in_words(contact.created_at) %></div>
  <div class="panel-body">
    <div class="btn-group" role="button" aria-label="...">
      <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatecontact_<%= contact.id %>">Edit</button>
      <%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" , remote: true%>
    </div>
  </div>
  <!-- Modal -->
  <%= form_for(contact, :method => :put , remote: true) do |f| %>
      <div class="modal fade" id="myupdatecontact_<%= contact.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Contact Update</h4>
            </div>
            <div class="modal-body">
              <div class="field">
                <%= f.label :Title %><br>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="field">
                <%= f.label :Content %><br>
                <%= f.text_area :contents , class: "form-control"%>
              </div>
              <div class="field">
                <%= f.label :MainContent %><br>
                <%= f.text_area :main_contents , class: "form-control"%>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= submit_tag "Update", class:"btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <!-- modal -->

</div>

app/views/contacts/create.js.erb
$("#myresearch").modal('hide');
$(".research_name").val('');
$(".research_contents").val('');
$(".research_main_contents").val('');
$("#my_research").prepend('<%= j render @research %>')
$("#research_<%= @research.id %>").hide().fadeIn(1000)

app/views/contacts/destroy.js.erb
$("#research_<%= @research.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/contacts/edit.html.erb
<%= form_for(@researches) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("contents") %></p>
    <p><%= form.text_area("contents") %></p>
    <p><%= form.label("main_containts") %></p>
    <p><%= form.text_area("main_containts") %></p>
    <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all research", research_path) %></p>

app/views/contacts/index.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="my_contact">
        <ul class="nav navbar-nav">
          <%= render @contacts %>
        </ul>
        </ul>
      </div>
    </div><!--/.row -->
  </div><!--/.container -->
<%= link_to("Add New Menu Item", new_research_path) %>

app/views/contacts/new.html.erb
<%= form_for(Research.new) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("name") %></p>
    <p><%= form.label("contents") %></p>
    <p><%= form.text_area("contents") %></p>
    <p><%= form.label("Main Contents") %></p>
    <p><%= form.text_area("main_contents") %></p>
    <p><%= form.submit %></p>
<% end %>
<%= link_to("Back to all entries", researches_path) %>

app/views/contacts/show.html.erb
<h2><%= @research.title %></h2>
<p><%= @research.contents %></p>
<p><%= @research.containts %></p>
<p><%= link_to("Edit this entry", edit_research_path(@research)) %></p>
<p><%= link_to("Back to all entries", research_path) %></p>

app/views/contacts/update.js.erb
$("#myupdateresearch_<%= @research.id %>").modal('hide');
$("#research_<%= @research.id %>").fadeOut(500, function(){

    $(this).remove();
    $("#my_research").prepend('<%= j render @research %>');
});

app/views/home/index.html.erb
<!-- Navigation
================================================== -->
<div class="navbar navbar-default navbar-static-top" role="navigation" xmlns="http://www.w3.org/1999/html">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% for entry in @entries %>
              <li><a href="#<%= entry.title %>"><%= entry.title %></a></li>
          <% end %>
        </ul>
      </div>
    </div><!--/.row -->
  </div><!--/.container -->
</div>
</header>
<!--End Header-->
<!--start wrapper-->
<div class="wrapper">
  <div class="slider-wrapper">
    <div class="slider">
      <div class="fs_loader"></div>
      <div class="slide">
        <!--1- slide background-->
        <%= image_tag "fraction-slider/gadgets/laptop-lg.png", width: 800, height: 750, data: { position: "-30,550", in: "bottom", delay: "500", out: "fade"} %>
       <!-- <img src="assets/fraction-slider/gadgets/laptop-lg.png" data-position="-30,550" data-in="bottom" data-delay="500" data-out="fade"  width="800" height="750"> -->                                    <!--3- laptop-->

        <p class="para-new" data-position="10,600" data-in="top"  data-out="Right" data-delay="">Mapunity News</p>
      </div>

      <div class="slide">
        <%= image_tag "fraction-slider/build.png", width: 1920,  data: { in: "fade" , out: "fade"} %>
       <!-- <img src="assets/fraction-slider/build.png" data-in="fade" data-out="fade" width="1920" height="auto"/> -->
        <p class="claim  theme-colored" data-position="110,250" data-in="left" data-out="Right" data-delay="2500">Mapunity News</p>
        <%= image_tag "fraction-slider/gadgets/laptop.png", width: 456, height: 272, data: { position: "103,1180", in: "bottom", delay: "400", out: "bottom"} %>
        <!-- <img src="assets/fraction-slider/gadgets/laptop.png" width="456" height="272" data-position="103,1180" data-in="bottom" data-out="bottom" data-delay="400"> -->
        <%= image_tag "fraction-slider/gadgets/mack.png", width: 357, height: 313, data: { position: "60,1040", in: "top", delay: "200", out: "bottom"} %>
       <!-- <img src="assets/fraction-slider/gadgets/mack.png" width="357" height="313" data-position="60,1040" data-in="top" data-out="bottom" data-delay="200"> -->
        <%= image_tag "fraction-slider/gadgets/ipad.png", width: 120, height: 170, data: { position: "120,1030", in: "left", delay: "300", out: "left"} %>
      <!--  <img src="assets/fraction-slider/gadgets/ipad.png" width="120" height="170" data-position="230,1030" data-in="left" data-delay="300" data-out="left"> -->
        <%= image_tag "fraction-slider/gadgets/smartphone.png", width: 70, height: 140, data: { position: "270,1320", in: "right", delay: "300", out: "right"} %>
       <!-- <img src="assets/fraction-slider/gadgets/smartphone.png" width="70" height="140" data-position="270,1320" data-in="right" data-delay="300" data-out="right"> -->
        <div class="para-2"	data-position="200,250" data-in="left" data-out="right" data-delay="3000">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur consequatur consequuntur debitis
          delectus nostrum quam quod reiciendis sit!
        </div>

      </div>
      <!--
      <div class="slide">
          <img src="images/fraction-slider/fraction_6.png" data-in="fade" data-out="fade" width="1920" height="auto">

          <p class="claim light-pink" data-position="50,1050" data-in="top"  data-out="top" data-ease-in="jswing">Latest News</p>

          <p class="teaser turky" data-position="120,1180" data-in="left" data-delay="1500">Mapunity News</p>

          <p class="teaser turky" data-position="170,1180" data-in="left"  data-delay="3000">full control over each element</p>

          <img src="images/fraction-slider/slider-girl.png" width="480" height="480" data-position="-20,250" data-in="right" data-delay="500" data-out="fade" style="width:auto; height:auto">

          <a href=""	class="slider-read" data-position="340,1330" data-in="bottom" data-out="top" data-delay="6500">download Now</a>
      </div> -->
    </div>
  </div>
  <!--End Slider-->
  <!--- --->
  <div class="info_service" id="Video">
    <div class="container">
      <div class="row sub_content">
        <div class="col-lg-12">
          <div class="dividerHeading">
            <h4><span>Video</span></h4>
          </div>
          <% for gallery in @galleries %>
          <div class="col-lg-6">
            <h2><%= gallery.title %></h2>
            <p><%= gallery.content %></p>
          </div>
          <div class="col-lg-6">
            <figure>
            <iframe width="560" height="315" src="<%= gallery.url %>" frameborder="0" allowfullscreen></iframe>
          </figure>
          </div>
          <% end %>
        </div><!-- TESTIMONIALS END -->
        </div>
      </div>
    </div>
  <div class="info_service" id="Blog">
    <div class="container">
      <div class="row sub_content">
        <div class="col-lg-12">
          <div class="dividerHeading">
            <h4><span>Blog</span></h4>
          </div>
          <section class="content blog">
            <div class="container">
              <div class="row">
                <div class="col-xs-12">
                  <div class="blog_medium">
                    <% for blog in Blog.all.order("id desc").limit(1).each %>
                        <article class="post">
                          <div class="post_date">

                            <span class="day"><%= blog.created_at.strftime("%d") %></span>
                            <span class="month"><%= blog.created_at.strftime("%b") %></span>

                          </div>

                          <figure class="post_img">
                              <%= image_tag blog.image_url(:large_avatar) if blog.image? %>
                          </figure>
                          <div class="post_content">
                            <div class="post_meta">
                              <h2>
                                <%= blog.title %>
                              </h2>
                              <div class="metaInfo">
                                <span><i class="fa"></i> Time :<%= blog.created_at.strftime("%H:%M") %> </span>
                                <span><i class="fa"></i> Year :<%= blog.created_at.strftime("%Y") %></span>
                              </div>
                            </div>
                            <p><%= blog.short_contents %></p>
                            <div class="text-right"><a class="btn btn-small btn-default" href="<%=	blogs_path  %>">Read More</a></div>

                          </div>

                        </article>

                    <% end %>
                  </div>

                </div>
              </div>
            </div> <!--/.container-->
          </section>
          </div>
        </div>
      </div>
</div>
  <!-- -->
  <!--start info service-->
<div class="info_service" id="Research">
  <div class="container">
    <div class="row sub_content">
      <div class="col-md-12">
        <div class="dividerHeading">
          <h4><span>Research</span></h4>
        </div>
      </div>
          <div class="rs_box">
            <% for research in @researches %>
            <div class="col-md-3 col-sm-6">
              <div class="serviceBox_1">
                <div class="icon_service">
                  <i class="fa fa-home"></i>

                  <h3><%= research.name %></h3>
                </div>
                <div class="fr_content">
                  <p>
                    <%= research.contents %>
                  </p>

                  <a class="read" href="#" data-toggle="modal" data-target="#myBtn_<%= research.id %>">Read more</a>
                  <div class="modal fade" id="myBtn_<%= research.id %>" role="dialog">
                    <div class="modal-dialog">

                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title"><%= research.name %></h4>
                        </div>
                        <div class="modal-body">
                          <p><%= research.contents %><%= research.main_contents %></p>
                        </div>

                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>

    </div>
  </div>
</div>
  <!--end info service-->

  <!--Start Technology -->
  <div id="Technology" class="content-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div>
            <h4><span  style="color: #fff !important;">Technology</span></h4>
          </div>
        </div>
      </div> <!-- /.row -->

      <div class="row sub_content">
        <% for technology in @technologies %>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <div class="serviceBox_2">
            <h3><%= technology.title %></h3>
            <p><%= technology.contents %>.</p>
          </div>
        </div>
        <% end %>
      </div>

    </div>
  </div>
  <!--End Technology -->
  <!--Start People-->
  <div class="info_service" id="People">
  <div class="latest_work">
    <div class="container">
      <div class="row sub_content">
        <div class="carousel-intro">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dividerHeading">
              <h4><span>People</span></h4>
            </div>
            <div class="carousel-navi">
              <div id="work-prev" class="arrow-left jcarousel-prev"><i class="fa fa-angle-left"></i></div>
              <div id="work-next" class="arrow-right jcarousel-next"><i class="fa fa-angle-right"></i></div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
        <!-------     meet the tema ------->
        <div class="jcarousel recent-work-jc">
          <ul class="jcarousel-list">
            <!-- Recent Work Item -->
            <% for member in @members %>
            <li class="col-lg-3 col-md-3 col-sm-6">

              <figure>
                <div class="eve-team">
                  <div class="pic">
                    <%= image_tag member.image_url(:large_avatar) if member.image? %>
                    <div class="social_media_team">
                    </div>
                  </div>
                  <div class="team_prof">
                    <h3 class="names"><%= member.name%></h3>
                    <p class="description">
                      <%= member.description%>
                    </p>
                  </div>
                </div>

              </figure>

            </li>
                <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>
  </div>
  <!--Start recent work-->
</div>
<script>
    $(document).ready(function(){
        $("#myBtn").click(function(){
            $("#myModal").modal();
        });
        $("#myBtn1").click(function(){
            $("#myModal1").modal();
        });

        $("#traffic").click(function(){
            $("#myModal-traffic").modal();
        });
        $("#city").click(function(){
            $("#myModal-city").modal();
        });
        $("#digital").click(function(){
            $("#myModal-digital").modal();
        });
        $("#Health").click(function(){
            $("#myModal-Health").modal();
        });
        $("#Safety").click(function(){
            $("#myModal-Safety").modal();
        });
        $("#Environment").click(function(){
            $("#myModal-Environment").modal();
        });
        $("#Education").click(function(){
            $("#myModal-Education").modal();
        });
        $("#Gender").click(function(){
            $("#myModal-Gender").modal();
        });
        $("#Economy").click(function(){
            $("#myModal-Economy").modal();
        });
        $("#Market").click(function(){
            $("#myModal-Market").modal();
        });
    });

</script>
<!-- Start Style Switcher
<div class="switcher"></div>
<!-- End Style Switcher -->
<script>
    $(window).load(function(){
        $('.slider').fractionSlider({
            'fullWidth': 			true,
            'controls': 			true,
            'responsive': 			true,
            'dimensions': 			"1920,450",
            'increase': 			true,
            'pauseOnHover': 		true,
            'slideEndAnimation': 	true,
            'autoChange':           true
        });
    });
</script>