config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources "entries"
  resources "researches"
  resources "technologies"
  resources "paintings"
  resources "members"
  resources "galleries"
  resources "blogs"
  resources "contacts"
  root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :title , :short_contents , :main_contents
  Blog.all.order("id desc").limit(1).each do |d|

  end
  def create
    Blog.create(blog_params)
  end
  private

  def blog_params
    params.require(:blog).permit(:image ,:title ,:short_contents , :main_contents)
  end
  belongs_to :entry
  mount_uploader :image, BlogUploader
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates_presence_of :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_presence_of :image , :name , :description
  def create
    Member.create(member_params)
  end
  private

  def member_params
    params.require(:member).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/new.rb
class New < ActiveRecord::Base

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  def create
    Painting.create(painting_params)
  end
  private

  def painting_params
    params.require(:painting).permit(:image)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/person.rb
class Person < ActiveRecord::Base
  def create
    Person.create(person_params)
  end
  private

  def person_params
    params.require(:people).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/research.rb
class Research < ActiveRecord::Base
  validates_presence_of :name , :contents , :main_contents
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title , :contents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @entries = Entry.all
    @blogs = Blog.all
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params["id"])
  end
  def create
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def edit
    @blog = Blog.find(params["id"])
  end
  def update
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.find(params["id"])
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def destroy
    blog = Blog.find(params["id"])
    @blog= Blog.destroy(blog)
    respond_to do |format|
      format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
      format.json { render :show, status: :ok, location: @blog }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to entries_path
    end
    @entry = Entry.new
    @entries = Entry.all
    @researches = Research.all
    @technologies = Technology.all
    @paintings = Painting.all
    @members = Member.all
    @blogs =Blog.all
    @galleries = Gallery.all
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
    def index
      @technologies = Technology.all
    end

    def show
      @technology = Technology.find(params["id"])
    end
    def create
      technology_params = params[:technology].permit(:title, :contents)
      @technology = Technology.new(technology_params)
      respond_to do |format|
        if @technology.save
          format.html { redirect_to(entries_path(@technology), notice: 'devise was successfully updated.' ) }
          format.json { render :show, status: :ok, location: @technology }
          format.js
        else
          format.html { render :new }
          format.json { render json: @technology.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
    def edit
      @technology = Technology.find(params["id"])
    end
    def update
      technology_params = params[:technology].permit(:title, :contents)
      @technology = Technology.find(params["id"])
      respond_to do |format|
        if @technology.update(technology_params)
          format.html { redirect_to(entries_path(@technology), notice: 'devise was successfully updated.' ) }
          format.json { render :show, status: :ok, location: @technology }
          format.js
        else
          format.html { render :new }
          format.json { render json: @technology.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
    def destroy
      technology = Technology.find(params["id"])
      @technology= Technology.destroy(technology)
      respond_to do |format|
        format.html { redirect_to(entries_path(@technology), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @technology }
        format.js
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_technology.html.erb
<div class="col-sm-4 col-md-4 col-lg-4" id="technology_<%= technology.id %>">
  <div class="serviceBox_2">
    <h3><%= best_in_place technology, :title %></h3>
    <p><%= best_in_place technology, :contents %>.</p>
  </div>
<div class="panel-body hidden" id="technology_div_<%= technology.id %>">
  <div class="btn-group" role="button" aria-label="...">
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatetechnology_<%= technology.id %>">Edit</button>
    <%= link_to 'Delete', technology, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" , remote: true%>
  </div>
</div>
  <script>
      $("#technology_edit_btn").click(function() {
          $("#technology_div_<%= technology.id %>").removeClass('hidden');
          $("#technology_cancel_btn").removeClass('hidden');
      });
      $("#technology_cancel_btn").click(function() {
          $("#technology_div_<%= technology.id %>").addClass('hidden');
          $("#technology_cancel_btn").addClass('hidden');
      });
      $("#technology_up_btn").click(function() {
          $("#technology_div_<%= technology.id %>").addClass('hidden');
          $("#technology_cancel_btn").addClass('hidden');
      });
  </script>
<!-- Modal -->
<%= form_for(technology, :method => :put , remote: true) do |f| %>
    <div class="modal fade" id="myupdatetechnology_<%= technology.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Technology Update</h4>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.label :Title %><br>
              <%= f.text_field :title, autofocus: true ,:required => true, placeholder: "Please input tilte" , :style => "font-size:small;" , class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :Content %><br>
              <%= f.text_area :contents ,:required => true, placeholder: "Maximum 250 words" , :style => "font-size:small;" , :maxlength => 250, :rows => 4, class: "form-control"%>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Update", class:"btn btn-primary" , id:"technology_up_btn" %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<!-- modal -->
</div>

app/views/technologies/create.js.erb
$("#mytechnology").modal('hide');
$(".technology_title").val('');
$(".technology_contents").val('');
$("#my_technology").prepend('<%= j render @technology %>')
$("#technology_<%= @technology.id %>").hide().fadeIn(1000)

app/views/technologies/destroy.js.erb
$("#technology_<%= @technology.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/technologies/edit.html.erb
<%= form_for(@technologies) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("contents") %></p>
    <p><%= form.text_area("contents") %></p>
    <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this research", technology_path(@technologies)) %></p>
<p><%= link_to("Back to all research", technologies_path) %></p>

app/views/technologies/index.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% for technology in @technologies %>
              <li><%= link_to(technology.title, technology_path(technology)) %></li>
          <% end %>
        </ul>
        </ul>
      </div>
    </div><!--/.row -->
  </div><!--/.container -->
<%= link_to("Add New Menu Item", new_technology_path) %>

app/views/technologies/new.html.erb
<%= form_for(Technology.new) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("contents") %></p>
    <p><%= form.text_area("contents") %></p>
    <p><%= form.submit %></p>
<% end %>

<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/technologies/show.html.erb
<h2><%= @technologies.title %></h2>
<p><%= @technologies.contents %></p>
<p><%= link_to("Edit this entry", edit_technology_path(@technologies)) %></p>
<p><%= link_to("Back to all entries", technologies_path) %></p>

app/views/technologies/update.js.erb
$("#myupdatetechnology_<%= @technology.id %>").modal('hide');
$("#technology_<%= @technology.id %>").fadeOut(500, function(){

    $(this).remove();
    $("#my_technology").prepend('<%= j render @technology %>');
});