config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources "entries"
  resources "researches"
  resources "technologies"
  resources "paintings"
  resources "members"
  resources "galleries"
  resources "blogs"
  resources "contacts"
  root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :title , :short_contents , :main_contents
  Blog.all.order("id desc").limit(1).each do |d|

  end
  def create
    Blog.create(blog_params)
  end
  private

  def blog_params
    params.require(:blog).permit(:image ,:title ,:short_contents , :main_contents)
  end
  belongs_to :entry
  mount_uploader :image, BlogUploader
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates_presence_of :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_presence_of :image , :name , :description
  def create
    Member.create(member_params)
  end
  private

  def member_params
    params.require(:member).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/new.rb
class New < ActiveRecord::Base

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  def create
    Painting.create(painting_params)
  end
  private

  def painting_params
    params.require(:painting).permit(:image)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/person.rb
class Person < ActiveRecord::Base
  def create
    Person.create(person_params)
  end
  private

  def person_params
    params.require(:people).permit(:image ,:name ,:description)
  end
  belongs_to :entry
  mount_uploader :image, ImageUploader
end

app/models/research.rb
class Research < ActiveRecord::Base
  validates_presence_of :name , :contents , :main_contents
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title , :contents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @entries = Entry.all
    @blogs = Blog.all
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params["id"])
  end
  def create
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def edit
    @blog = Blog.find(params["id"])
  end
  def update
    blog_params = params[:blog].permit(:image, :title, :short_contents, :main_contents)
    @blog = Blog.find(params["id"])
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @blog }
        format.js
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  def destroy
    blog = Blog.find(params["id"])
    @blog= Blog.destroy(blog)
    respond_to do |format|
      format.html { redirect_to(entries_path(@blog), notice: 'devise was successfully updated.' ) }
      format.json { render :show, status: :ok, location: @blog }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to entries_path
    end
    @entry = Entry.new
    @entries = Entry.all
    @researches = Research.all
    @technologies = Technology.all
    @paintings = Painting.all
    @members = Member.all
    @blogs =Blog.all
    @galleries = Gallery.all
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index
      @members = Member.all
    end

    def show
      @member = Member.find(params["id"])
    end
    def create
      member_params = params[:member].permit(:image , :name ,:description)
      @member = Member.new(member_params)
      respond_to do |format|
        if @member.save
          format.html { redirect_to(entries_path(@member), notice: 'devise was successfully updated.' ) }
          format.json { render :show, status: :ok, location: @member }
          format.js
        else
          format.html { render :new }
          format.json { render json: @member.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
    def edit
      @member = Member.find(params["id"])
    end
    def update
      member_params = params[:member].permit(:image , :name ,:description)
      @member = Member.find(params["id"])
      respond_to do |format|
        if @member.update(member_params)
          format.html { redirect_to(entries_path(@member), notice: 'devise was successfully updated.' ) }
          format.json { render :show, status: :ok, location: @member }
          format.js
        else
          format.html { render :new }
          format.json { render json: @member.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
    def destroy
      member = Member.find(params["id"])
      @member= Member.destroy(member)
      respond_to do |format|
        format.html { redirect_to(entries_path(@member), notice: 'devise was successfully updated.' ) }
        format.json { render :show, status: :ok, location: @member }
        format.js
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/research_helper.rb
module ResearchHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/members/_member.html.erb
 <!-- Recent Work Item -->
  <li class="col-lg-3 col-md-3 col-sm-6" id="member_<%= member.id %>">
    <figure>
      <div class="eve-team">
        <div class="pic">
          <%= image_tag member.image_url(:large_avatar) if member.image? %>
          <div class="social_media_team">
          </div>
        </div>
        <div class="team_prof">
          <h3 class="names"><%=member.name%></h3>
          <p class="description">
            <%= member.description%>
          </p>
        </div>
        <div class="panel-body">
          <div class="btn-group hidden" role="button" aria-label="..." id="member_div_<%= member.id %>">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatemember_<%= member.id %>">Edit</button>
            <%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" , remote: true%>
          </div>
        </div>
        <script>
            $("#member_edit_btn").click(function() {
                $("#member_div_<%= member.id %>").removeClass('hidden');
                $("#member_cancel_btn").removeClass('hidden');
            });
            $("#member_cancel_btn").click(function() {
                $("#member_div_<%= member.id %>").addClass('hidden');
                $("#member_cancel_btn").addClass('hidden');
            });
        </script>
        <!-- Modal -->
        <%= form_for(member, :html => {:multipart => true} , :method => :put , remote: true , authenticity_token: true) do |f| %>
            <div class="modal fade" id="myupdatemember_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Member Update</h4>
                  </div>
                  <div class="modal-body">
                    <div class="field">
                      <%= f.label :Photo %><br>
                      <%= f.file_field :image, autofocus: true , class: "form-control" %>
                    </div>
                    <div class="field">
                      <%= f.label :Name %><br>
                      <%= f.text_field :name ,:required => true, placeholder: "Please input name" , :style => "font-size:small;" , class: "form-control"%>
                    </div>
                    <div class="field">
                      <%= f.label :About %><br>
                      <%= f.text_area :description ,:required => true, :maxlength => 300, :rows => 4 , placeholder: "Maximum 300 words" , :style => "font-size:small;" , class: "form-control"%>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= submit_tag "Update", class:"btn btn-primary" , id:"member_up_btn" %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
        <!-- modal -->

      </div>

    </figure>

  </li>

app/views/members/create.js.erb
$("#mymember").modal('hide');
$(".member_image").val('');
$(".member_name").val('');
$(".member_description").val('');
$("#my_member").prepend('<%= j render @member %>')
$("#member_<%= @member.id %>").hide().fadeIn(1000)

app/views/members/destroy.js.erb
$("#member_<%= @member.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/members/edit.html.erb
<%= form_for(@member) do |form| %>
    <p>
      <%= form.file_field :image %>
      <%= form.text_field :name %>
      <%= form.text_area :description%>
    <p><%= form.submit %></p>
    </p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/members/index.html.erb
<% for member in @members %>
    <%= image_tag member.image_url(:thumb) if member.image? %>
    <%= member.name%>
    <%= member.description%>
<% end %>

app/views/members/new.html.erb
<%= form_for Member.new, :html => {:multipart => true} do |f| %>
    <p>
      <%= f.file_field :image %>
      <%= f.text_field :name %>
      <%= f.text_area :description %>
    </p>
    <p><%= f.submit %></p>
<% end %>

app/views/members/show.html.erb
<%= image_tag @member.image_url(:thumb) if @member.image? %>
<%= @member.name%>
<%= @member.description%>
<p><%= link_to("Edit this entry", edit_painting_path(@member)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/members/update.js.erb
$("#myupdatemember_<%= @member.id %>").modal('hide');
$("#member_<%= @member.id %>").fadeOut(500, function(){

    $(this).remove();
    $("#my_member").prepend('<%= j render @member %>');
});